import type { StudyPack, Squad, UserProfile } from "./types";

export const MOCK_STUDY_PACK: StudyPack = {
  id: "demo-newtons-laws",
  ownerId: "demo-alex",
  topic: "Newton's Second Law",
  sourceType: "notes",
  overview:
    "Newton's Second Law explains how force, mass and acceleration are connected. Push harder and an object accelerates more. If the object is heavier, the same push creates less acceleration.",
  analogies: [
    "Think of a shopping trolley. An empty trolley speeds up easily, but a full trolley needs more force.",
    "A football moves quickly from a small kick because it has low mass.",
    "A loaded suitcase needs a stronger pull to speed up at the same rate.",
  ],
  keyPoints: [
    "Force causes acceleration.",
    "More force means more acceleration if mass stays the same.",
    "More mass means less acceleration for the same force.",
    "The formula is F = ma.",
  ],
  flashcards: [
    { front: "What is Newton's Second Law?", back: "Force equals mass times acceleration, F = ma." },
    { front: "What happens if force increases?", back: "Acceleration increases if mass stays the same." },
    { front: "What happens if mass increases?", back: "Acceleration decreases for the same force." },
  ],
  quiz: [
    {
      question: "If force increases while mass stays the same, what happens to acceleration?",
      choices: ["It decreases", "It stays the same", "It increases", "It becomes zero"],
      correctIndex: 2,
    },
    {
      question: "Which formula matches Newton's Second Law?",
      choices: ["F = ma", "E = mc2", "V = IR", "P = IV"],
      correctIndex: 0,
    },
    {
      question: "A heavier object needs what to accelerate at the same rate?",
      choices: ["Less force", "More force", "No force", "Less mass"],
      correctIndex: 1,
    },
  ],
  plan: [
    "Read the simple explanation for 2 minutes.",
    "Review the key points for 2 minutes.",
    "Try the flashcards for 3 minutes.",
    "Answer the quiz for 3 minutes.",
    "Revise one weak point tomorrow.",
  ],
};

export const MOCK_LEADERS: (UserProfile & { id: string })[] = [
  {
    id: "maya",
    uid: "maya",
    email: "maya@studyflow.demo",
    displayName: "Maya",
    onboardingComplete: true,
    learningStyle: "examEdge",
    accessibility: {
      reduceMotion: false,
      dyslexiaFont: false,
      textSize: "normal",
      lineSpacing: "normal",
      lowStimulation: false,
    },
    xp: 1850,
    level: 4,
    streakCount: 8,
    streakFreezeAvailable: true,
    lastActiveDate: null,
    squadId: "sphere-physics-bros",
    badges: [],
    basicInfo: { headline: "", bio: "", location: "" },
    experience: [],
    qualifications: [],
    languages: [],
    skills: [],
  },
  {
    id: "alex",
    uid: "alex",
    email: "alex@studyflow.demo",
    displayName: "Alex",
    onboardingComplete: true,
    learningStyle: "picturePath",
    accessibility: {
      reduceMotion: false,
      dyslexiaFont: false,
      textSize: "normal",
      lineSpacing: "normal",
      lowStimulation: false,
    },
    xp: 1620,
    level: 4,
    streakCount: 7,
    streakFreezeAvailable: true,
    lastActiveDate: null,
    squadId: "sphere-physics-bros",
    badges: [],
    basicInfo: { headline: "", bio: "", location: "" },
    experience: [],
    qualifications: [],
    languages: [],
    skills: [],
  },
  {
    id: "jordan",
    uid: "jordan",
    email: "jordan@studyflow.demo",
    displayName: "Jordan",
    onboardingComplete: true,
    learningStyle: "focusFlow",
    accessibility: {
      reduceMotion: false,
      dyslexiaFont: false,
      textSize: "normal",
      lineSpacing: "normal",
      lowStimulation: false,
    },
    xp: 1400,
    level: 3,
    streakCount: 5,
    streakFreezeAvailable: true,
    lastActiveDate: null,
    squadId: "sphere-physics-bros",
    badges: [],
    basicInfo: { headline: "", bio: "", location: "" },
    experience: [],
    qualifications: [],
    languages: [],
    skills: [],
  },
];

export const MOCK_SPHERES: (Squad & { id: string; score: number; members: number })[] = [
  {
    id: "sphere-bio-legends",
    name: "Bio Legends",
    memberIds: ["maya", "priya", "sam", "lee"],
    totalXp: 6440,
    weeklyChallenge: "Complete 3 study packs before Friday",
    score: 92,
    members: 4,
  },
  {
    id: "sphere-physics-bros",
    name: "Physics Bros",
    memberIds: ["maya", "alex", "jordan", "sam", "priya"],
    totalXp: 6120,
    weeklyChallenge: "Complete 3 study packs before Friday",
    score: 86,
    members: 5,
  },
  {
    id: "sphere-maths-monsters",
    name: "Maths Monsters",
    memberIds: ["jordan", "sam", "lee", "noah", "aisha", "riley"],
    totalXp: 5880,
    weeklyChallenge: "Review 5 weak topics as a group",
    score: 81,
    members: 6,
  },
];
